export const blogList = [
  {
    id: 1,
    title: 'Web-dev ideas for the adventurous',
    category: 'development',
    subCategory: ['frontend', 'ui/ux', 'design'],
    description:
      "Web developers have increasingly been on the look out for tools that will help them to better enhance their creativity. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Walter White',
    authorAvatar: '/assets/images/avatar.svg',
    createdAt: 'Jan 03, 2023',
    cover: '/assets/images/designer-1.jpg',
  },
  {
    id: 2,
    title: 'Milan, the European city that never sleeps',
    category: 'travel',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "Milan. Fashion Capital of the world and one of the beacons of North Italian flare and creativity. The food, is one of its many strong points. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Walter White',
    authorAvatar: '/assets/images/avatar.svg',
    createdAt: 'Jan 03, 2023',
    cover: '/assets/images/milan.jpg',
  },
  {
    id: 3,
    title: 'Online Shopping – An Alternative to Shopping at the Mall',
    category: 'shopping',
    subCategory: ['e-commerce store', 'clothing', 'shopping store'],
    description:
      "When do we want it? We need it now. The motto of most online shoppers as opposed to the mall garden variety. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Walter White',
    authorAvatar: '/assets/images/avatar.svg',
    createdAt: 'Jan 03, 2023',
    cover: '/assets/images/online.jpg',
  },
  {
    id: 4,
    title: 'The Adventure in YOU',
    category: 'adventure',
    subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
    description:
      "Seeking out adventure. The trials and tribulations of the fiercely travel seekers of today. One can just think up a destination.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Walter White',
    authorAvatar: '/assets/images/avatar.svg',
    createdAt: 'Jan 03, 2023',
    cover: '/assets/images/lifestyle.jpg',
  },
  {
    id: 5,
    title: 'Hold the fort!! loaded BBQ-Baked Potatoes',
    category: 'cooking',
    subCategory: ['bbq', 'food', 'lifestyle'],
    description:
      "You are alone at home, you've got Netflix ready and you think to yourself shall I order some food or make something myself...this meal is a definite go to!. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Walter White',
    authorAvatar: '/assets/images/avatar.svg',
    createdAt: 'Jan 03, 2023',
    cover: '/assets/images/bbq-potatoes.jpg',
  },
  {
    id: 6,
    title: 'To the beach or not to the beach?',
    category: 'travel',
    subCategory: ['beaches', 'sea', 'holidays'],
    description:
      "That happy place you imagine when you are in a complete stressed out moment is the beach 9 out of 10 times thats where we will go.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Walter White',
    authorAvatar: '/assets/images/avatar.svg',
    createdAt: 'Jan 03, 2023',
    cover:
      '/assets/images/sea-art.jpg',
  },
  {
    id: 7,
    title: 'Is it an ism or is it art?',
    category: 'art',
    subCategory: ['skill', 'design', 'passion'],
    description:
      "A song once echoed those very words. To seek out an art pice, or phrase or lyric is to modernism it to art-ism? or is that a word.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Walter White',
    authorAvatar: '/assets/images/avatar.svg',
    createdAt: 'Jan 03, 2023',
    cover: '/assets/images/graphic-2.jpg',
  },
  {
    id: 8,
    title: 'Is Marvel still the Marvel comic?',
    category: 'art',
    subCategory: ['Super-hero', 'Fantasy', 'Fable'],
    description:
      "The once powerhouse that bought Hollywood to its knees..the MCU otherwise known as the Marvel cinematic Universe. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Walter White',
    authorAvatar: '/assets/images/avatar.svg',
    createdAt: 'Jan 03, 2023',
    cover: '/assets/images/marvel.jpg',
  },
  {
    id: 9,
    title: 'NextJS is taking the dev world by storm',
    category: 'art',
    subCategory: ['Frameworks', 'Programming', 'Development'],
    description:
      "The latest iteration of NextJs was launched in November last year and with that winning huge amounts of existing developers over. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Walter White',
    authorAvatar: '/assets/images/avatar.svg',
    createdAt: 'Jan 03, 2023',
    cover: '/assets/images/Next.jpg',
  },
];